name: Create issues from TODOs

on:
  workflow_dispatch:
    inputs:
      importAll:
        default: false
        required: false
        type: boolean
        description: Import all TODOs from the checked out branch.
  push:
    branches:
      - main
      - master
      - def-scene

permissions:
  issues: write
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Issue Bot
        uses: juulsn/todo-issue@main
        with:
          excludePattern: '^(node_modules/)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}